version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: miusuario
      POSTGRES_PASSWORD: miclave
      POSTGRES_DB: midb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres_data: